---
- hosts: aws
  tasks:
  - name: Install httpd service on aws server
    yum: name=httpd state=present
  - name: copy file to remote server
    template: src=httpd.conf dest=/etc/httpd/conf
    notify:
    - restart apache 
#  - name: make sure apache service automatically restart after reboot
#    service: name=httpd state=restarted enabled=yes
  handlers:
  - name: restart apache
    service: name=httpd state=restarted enabled=yes 
