#Ansible when variable is empty
- hosts: hotel
  tasks:
  - shell: cat /etc/temp.txt
    register: output
  - name: Ansible when variable is empty example
    debug:
      msg: "empty"
    when: output.stdout == ""
