---
kafka_url: http://apache.rediris.es/kafka
kafka_version: 2.0.0
kafka_package_name: 2.12-2.0.0
kafka_dir: /opt/kafka
configuration:
 port: 9092
 data_dir: /var/lib/kafka 
 log_dirs: /tmp/lib/kafka/kafka-logs
 log_path: /var/log/kafka
 network_threads: 3
 disk_threads: 8 
 num_partitions: 3
 so_snd_buff_bytes: 102400
 so_rcv_buff_bytes: 102400
 so_request_max_bytes: 104857600
 data_dir_recovery_threads: 1
 log_retention_hours: 24 
 log_retention_bytes: 1073741824
 log_segment_bytes: 1073741824
 log_retention_check_interval: 300000
 log_cleaner_enable: false
 zk_connection_timeout: 60000
 broker_id: 1

zookeeper:
 configuration:
  port: 2181

